default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bishop_test_development

test:
  <<: *default
  database: bishop_test_test

production:
  <<: *default
  database: bishop_test_production
  username: bishop_test
  password: <%= ENV['BISHOP_TEST_DATABASE_PASSWORD'] %>
